# Generated by Django 5.2.3 on 2025-06-18 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ration_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionsession',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='distributionsession',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
