# Generated by Django 5.2.3 on 2025-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ration_ticket', '0002_alter_distributionsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionsession',
            name='max_tokens',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='distributionsession',
            name='current_token',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
