# Generated by Django 5.2.3 on 2025-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ration_ticket', '0003_distributionsession_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
